
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LunchWars.Domain
{

using System;
    using System.Collections.Generic;
    
public partial class TripUser
{

    public int TripId { get; set; }

    public int UserId { get; set; }

    public bool Attended { get; set; }

    public bool IsDriving { get; set; }

    public int Votes { get; set; }



    public virtual Trip Trip { get; set; }

    public virtual User User { get; set; }

}

}
