
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LunchWars.Domain
{

using System;
    using System.Collections.Generic;
    
public partial class TripVote
{

    public int TripId { get; set; }

    public int RestaurantId { get; set; }

    public Nullable<int> UserId { get; set; }

    public Nullable<int> VoteTypeId { get; set; }



    public virtual Restaurant Restaurant { get; set; }

    public virtual Trip Trip { get; set; }

    public virtual User User { get; set; }

    public virtual VoteType VoteType { get; set; }

}

}
